
= Wirtschaftliches Potenzial und Marktabgrenzung...(weiter ausbauen)

- wieviel an kosten kann ca. gespart werden für ein objekt wie das four
- anforderungen an BAP für ifc modell

Die wirtschaftliche und ökologische Relevanz intelligenter Verschattungslösungen zeigt sich insbesondere bei großen, prestigeträchtigen Immobilien in zentraler Lage. 
// Da diese oft eine hohe verglaste Fläche aufweisen. 
Exemplarisch verdeutlicht dies die Stadt Frankfurt am Main, in der bis zum Jahr 2040 die Errichtung von 14 neuen Hochhäusern mit einer Höhe von über 60 Metern geplant ist~@frankfurt_hep_2024_anhang2. Das Marktpotenzial für umgebungsabhängige Verschattungssimulationen beschränkt sich jedoch nicht auf Hochhäuser. Generell profitieren sämtliche Zweckgebäude mit großen Fensterflächen und einer zentralen Gebäudeautomation von diesen Technologien. In aktuellen Ausschreibungen wird eine prädiktive und intelligente Verschattung zunehmend als Standard gefordert. Gebäudeeigentümer verzeichnen dadurch einen erhöhten Gebäudewert, der aus einer gesteigerten Energieeffizienz und Nutzerzufriedenheit resultiert. Gleichzeitig profitieren Systemintegratoren von dem in dieser Arbeit angestrebten Prozess, da er eine kostengünstigere und effizientere Umsetzung der Verschattungssimulation ermöglicht.

Um das technische Potenzial des hier konzipierten Workflows einzuordnen, ist ein Abgleich mit dem Status quo am Markt sinnvoll. Etablierte Sonnenschutzhersteller, wie beispielsweise WAREMA, bieten die Berechnung der Jahresverschattung derzeit primär als kostenpflichtige Dienstleistung an. Eine Analyse gängiger Angebotstexte @warema_jahresverschattung_basispreis offenbart dabei signifikante prozessuale Defizite, welche durch den in dieser Arbeit fokussierten Open-Source-Ansatz gelöst werden sollen:

- Medienbrüche und manuelle Datenaufbereitung: Kommerzielle Dienstleister fordern häufig proprietäre CAD-Formate (wie Revit oder DWG) mit strikten Dateigrößenlimits von beispielsweise 250 Megabyte. Zudem muss die Fachplanung das Modell oftmals manuell bereinigen, etwa durch die Entfernung von Innenwänden oder Inventar, bevor es übermittelt werden kann. Ein durchgängiger, IFC-basierter Workflow zielt hingegen darauf ab, relevante Entitäten wie `IfcWindow` oder `IfcCurtainWall` automatisiert aus dem Open@bim#[]-Modell auszulesen, ohne durch künstliche Dateigrößen limitiert zu sein.

- Integration von Umgebungsdaten: Bei konventionellen Dienstleistern muss die Umgebung häufig manuell im 3D-Modell nachgebaut werden. Fehlen in den übermittelten CAD-Plänen detaillierte Höhenangaben zur Nachbarbebauung, resultiert dies in kostenpflichtigen Nachvermessungen. Der hier vorgestellte Prozess setzt stattdessen auf die direkte Integration frei verfügbarer CityGML- beziehungsweise CityJSON-Daten in die Simulationsumgebung.

- Kostenstruktur und räumliche Granularität: Das Preismodell kommerzieller Anbieter basiert in der Regel auf der Anzahl der zu berechnenden Verschattungszonen. Aus wirtschaftlichen Gründen werden in der Praxis daher oft große Fassadenbereiche zu einer einzigen Zone zusammengefasst, was unweigerlich zu stark konservativen Worst-Case-Annahmen auf Kosten der Tageslichtautonomie führt. Ein softwaregestützter Eigenbauansatz eliminiert diese Restriktion: Die Iteration über alle Fenster des Gebäudes verursacht eine höhere Rechenzeit, jedoch keine personellen Zusatzkosten, wodurch eine fenstergenaue Simulation auch bei Großprojekten realisierbar wird.

- Herstellerunabhängigkeit: Während kommerzielle Herstellerlösungen die errechneten Schattenverläufe meist über firmeneigene Software in herstellerspezifische Controller laden, ist der Output des hier konzipierten Proof of Concepts herstellerneutral. Die generierten Verschattungsdaten werden in einem offenen Format (CSV) bereitgestellt und können über standardisierte Schnittstellen in beliebige Automationsstationen integriert werden.

Zusammenfassend motivieren diese Marktbeschränkungen die Zielsetzung der vorliegenden Arbeit. Der angestrebte Workflow soll die Ermittlung der Jahresverschattung von einer manuellen, fehleranfälligen und oft proprietären Dienstleistung in einen transparenten, skalierbaren und herstellerunabhängigen Engineering-Prozess überführen.